import type { ProgramYaml } from "./model";

export const sampleProgram: ProgramYaml = {
  contract_version: "1.0.0",
  project_id: "prj_demo-studio",
  source: {
    file_name: "protocol.pdf",
    sha256: "0000000000000000000000000000000000000000000000000000000000000000",
    protocol_title: "示範用睡眠研究計畫書",
    protocol_version: "demo-1.0",
    protocol_date: "2026-07-19",
    extraction_method: "native-text",
    extracted_at: "2026-07-19T00:00:00Z",
  },
  terminology_sources: [
    {
      standard: "CDISC",
      model: "SDTM",
      publication: "CDISC SDTM Controlled Terminology",
      version: "2026-03-27",
      source_url: "https://evs.nci.nih.gov/ftp1/CDISC/SDTM/SDTM%20Terminology.txt",
      retrieved_at: "2026-07-19T00:00:00Z",
    },
  ],
  candidate_forms: [
    {
      candidate_id: "baseline-assessment",
      title: "基準評估",
      purpose: "示範欄位編輯、CDISC 對應與表單產製流程。",
      visit: "baseline",
      source_refs: [{ locator: "Section 8.2, page 42", confidence: "high" }],
    },
  ],
  selected_form: {
    candidate_id: "baseline-assessment",
    title: "基準評估表",
    purpose: "收集受試者基準資料。",
    visit: "baseline",
    approval_status: "approved",
    form_id: "baseline-assessment",
    schema_version: "0.1.0",
    schema_path: "forms/baseline-assessment/0.1.0/crf-schema.json",
    validation_report_path: "forms/baseline-assessment/0.1.0/validation-report.md",
    fields: [
      {
        concept_id: "age_years",
        label: "年齡",
        purpose: "記錄同意時的年齡。",
        data_type: "integer",
        required: true,
        unit: "years",
        range: { minimum: 18, maximum: 85 },
        options: [],
        source_refs: [{ locator: "Section 8.2, page 42", confidence: "high" }],
        inference: { kind: "protocol_explicit", rationale: null, confidence_percent: 100 },
        coding: {
          status: "matched",
          standard: "CDISC",
          model: "SDTM",
          implementation_guide: "SDTMIG v3.4",
          domain: "DM",
          variable: "AGE",
          version: "3.4",
          source_url: "https://www.cdisc.org/standards/foundational/sdtmig/sdtmig-v3-4",
          mapping_confidence_percent: 95,
        },
      },
      {
        concept_id: "biological_sex",
        label: "生理性別",
        purpose: "記錄 protocol 指定的生理性別選項。",
        data_type: "string",
        required: true,
        options: [
          { value: "F", label: "女" },
          { value: "M", label: "男" },
          { value: "U", label: "未知" },
        ],
        source_refs: [{ locator: "Section 8.2, page 42", confidence: "high" }],
        inference: { kind: "protocol_explicit", rationale: null, confidence_percent: 100 },
        coding: {
          status: "matched",
          standard: "CDISC",
          model: "SDTM",
          implementation_guide: "SDTMIG v3.4",
          domain: "DM",
          variable: "SEX",
          version: "2026-03-27",
          source_url: "https://evs.nci.nih.gov/ftp1/CDISC/SDTM/SDTM%20Terminology.txt",
          mapping_confidence_percent: 100,
          codelist: {
            name: "Sex",
            submission_value: "SEX",
            ncit_code: "C66731",
            extensible: false,
          },
          terms: [
            {
              value: "F",
              submission_value: "F",
              system: "https://ncit.nci.nih.gov",
              ncit_code: "C16576",
              label: "Female",
              version: "2026-03-27",
            },
            {
              value: "M",
              submission_value: "M",
              system: "https://ncit.nci.nih.gov",
              ncit_code: "C20197",
              label: "Male",
              version: "2026-03-27",
            },
            {
              value: "U",
              submission_value: "U",
              system: "https://ncit.nci.nih.gov",
              ncit_code: "C17998",
              label: "Unknown",
              version: "2026-03-27",
            },
          ],
        },
      },
      {
        concept_id: "investigator_note",
        label: "研究備註",
        purpose: "記錄不含直接識別資訊的研究備註。",
        data_type: "string",
        required: false,
        options: [],
        source_refs: [{ locator: "Section 10.1, page 60", confidence: "medium" }],
        inference: {
          kind: "inferred_supporting_field",
          rationale: "Protocol 明確要求記錄資料疑義。",
          confidence_percent: 85,
        },
        coding: {
          status: "not-applicable",
          rationale: "研究作業備註不對應提交用 CDISC 變數。",
        },
      },
    ],
  },
  unresolved_items: [],
  approvals: {
    clinical_meaning: {
      status: "approved",
      approved_by: "demo-user",
      approved_at: "2026-07-19T00:00:00Z",
    },
    form_contract: {
      status: "pending",
      approved_by: null,
      approved_at: null,
    },
  },
};
